var str5 = '<section class="footer-call-to-action">';
str5 += '	<section class="container">';
str5 += '	<div class="three-fourth">';
str5 += '		<h4>如果您想跟我们合作请与我们联系。</h4>';
str5 += '	</div>';
str5 += '	<div class="one-fourth">';
str5 += '		<a href="contact.html" class="button grey huge round">联系我们</a>';
str5 += '	</div>';
str5 += '	</section>';
str5 += '</section>';
document.write(str5);