var str3 = '<footer id="footer">';
//str3 += '		<section class="container">';
//str3 += '		<section class="one-third">';
//str3 += '		<h4>联系我们</h4>';
//str3 += '		<ul class="twitter-feeds">';
//str3 += '		</ul>';
//str3 += '		<p>';
//str3 += '			<a href="#">招贤纳士</a>';
//str3 += '		</p>';
//str3 += '	</section>';
//str3 += '		<section class="one-third">';
//str3 += '		<h4>关于产品</h4>';
//str3 += '		<ul>';
//str3 += '			<li><a href="blog-post.html">企业定制化软件收费规则。</a></li>';
//str3 += '			<li><a href="blog-post.html">企业定制化软件收费规则。</a></li>';
//str3 += '			<li><a href="blog-post.html">企业定制化软件收费规则。</a></li>';
//str3 += '			<li><a href="blog-post.html">企业定制化软件收费规则。</a></li>';
//str3 += '		</ul>';
//str3 += '		</section>';
//str3 += '		<section class="one-third">';
//str3 += '		<h4>满益商城</h4>';
//str3 += '		<div class="flickr-widget">';
//str3 += '		</div>';
//str3 += '		</section>';
//str3 += '		</section>';
str3 += '		</footer>';
document.write(str3);