var str4 = '<section id="copyrights">';
str4 += '	<section class="container">';
str4 += '					<div class="one-half">';
str4 += '						<p>';
str4 += '							Copyright &copy; 2014.Company name All rights reserved.';
str4 += '						</p>';
str4 += '					</div>';
str4 += '				<div class="one-half">';
str4 += '						<ul class="copyright_links">';
str4 += '						<li>';
str4 += '							<a href="index.html" title="Home">首页</a>';
str4 += '						</li>';
str4 += '						<li>';
str4 += '							<a href="about-us.html" title="About">关于我们</a>';
str4 += '						</li>';
str4 += '						<li>';
str4 += '							<a href="services.html" title="Blog">服务提供</a>';
str4 += '						</li>';
str4 += '					<li>';
str4 += '						<a href="portfolio-3.html" title="Contact">案例展示</a>';
str4 += '					</li>';
str4 += '				</ul>';
str4 += '				</div>';
str4 += '			</section>';
str4 += '			</section>';
document.write(str4);