var str = ' <div id="header-links">';
str += ' 	<div class="container">';
str += ' 		<div class="one-half">';
str += ' 		<ul class="contact-links">';
str += ' 				<li><a href="#"><i class="icon-home"></i>宁波高新区华森信息科技有限公司</a></li>';
str += ' 				<li><a href="#"><i class="icon-phone"></i>+987 654 321 </a></li>';
str += ' 				<li><a href="#"><i class="icon-map-marker"></i>mail@yoursite.com</a></li>';
str += ' 			</ul>';
str += ' 		</div>';
str += ' 		<div class="one-half">';
str += ' 			<ul class="social-links">';
//str += ' 				<li><a href="#" class="tooltip" title="Some Title"><i class="icon-twitter"></i></a></li>';
//str += ' 				<li><a href="#" class="tooltip" title="Some Title"><i class="icon-facebook"></i></a></li>';
//str += ' 				<li><a href="#" class="tooltip" title="Some Title"><i class="icon-linkedin"></i></a></li>';
//str += ' 				<li><a href="#" class="tooltip" title="Some Title"><i class="icon-google-plus"></i></a></li>';
//str += ' 				<li><a href="#" class="tooltip" title="Some Title"><i class="icon-skype"></i></a></li>';
//str += ' 				<li><a href="#" class="tooltip" title="Some Title"><i class="icon-dribbble"></i></a></li>';
//str += ' 				<li><a href="#" class="tooltip" title="Some Title"><i class="icon-pinterest"></i></a></li>';
//str += ' 				<li><a href="#" class="tooltip" title="Some Title"><i class="icon-tumblr"></i></a></li>';
str += ' 			</ul>';
str += ' 		</div>';
str += ' 	</div>';
str += ' </div>';
document.write(str);