var str1 = '<div class="head-wrapp">';
str1 += '		<a href="index.html" id="logo"><img src="images/logo.png" style="width:60px"/><span>   华夏天地博大精深  </span></a>';
str1 += '			<nav class="top-search">';
//str1 += '			<form action="404-error.html" method="get">';
//str1 += '				<button class="search-btn"></button>';
//str1 += '			<input class="search-field" type="text" value="Search"/>';
//str1 += '			</form>';
str1 += '		</nav>';
str1 += '	</div>';
document.write(str1);